export const ALL_COUNTRIES_SUCCESS = "ALL_COUNTRIES_SUCCESS";
export const ALL_COUNTRIES_FAIL = "ALL_COUNTRIES_FAIL";

export const GET_COUNTRIE_SUCCESS = "GET_COUNTRIE_SUCCESS";
export const GET_COUNTRIE_FAIL = "GET_COUNTRIE_FAIL";

export const FILTER_COUNTRIE_SUCCESS = "FILTER_COUNTRIE_SUCCESS";
export const FILTER_COUNTRIE_FAIL = "FILTER_COUNTRIE_FAIL";

export const FILTER_REGION_COUNTRIE_SUCCESS = "FILTER_REGION_COUNTRIE_SUCCESS";
export const FILTER_REGION_COUNTRIE_FAIL = "FILTER_REGION_COUNTRIE_FAIL";

export const SET_MODE_DARK = "SET_MODE_DARK";